# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'snmp_scanner_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SNMPScannerWindow(object):
    def setupUi(self, SNMPScannerWindow):
        SNMPScannerWindow.setObjectName("SNMPScannerWindow")
        SNMPScannerWindow.resize(928, 632)
        self.centralwidget = QtWidgets.QWidget(SNMPScannerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scanButton = QtWidgets.QPushButton(self.groupBox)
        self.scanButton.setIconSize(QtCore.QSize(24, 24))
        self.scanButton.setAutoDefault(False)
        self.scanButton.setFlat(False)
        self.scanButton.setObjectName("scanButton")
        self.gridLayout_3.addWidget(self.scanButton, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.hostsCBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostsCBox.sizePolicy().hasHeightForWidth())
        self.hostsCBox.setSizePolicy(sizePolicy)
        self.hostsCBox.setEditable(True)
        self.hostsCBox.setDuplicatesEnabled(False)
        self.hostsCBox.setObjectName("hostsCBox")
        self.gridLayout.addWidget(self.hostsCBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.communityCBox = QtWidgets.QComboBox(self.groupBox)
        self.communityCBox.setEditable(True)
        self.communityCBox.setObjectName("communityCBox")
        self.gridLayout.addWidget(self.communityCBox, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 2, 2, 1)
        self.stopButton = QtWidgets.QPushButton(self.groupBox)
        self.stopButton.setEnabled(True)
        self.stopButton.setIconSize(QtCore.QSize(24, 24))
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_3.addWidget(self.stopButton, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.scanResultsTableView = QtWidgets.QTableView(self.splitter)
        self.scanResultsTableView.setMouseTracking(True)
        self.scanResultsTableView.setMidLineWidth(0)
        self.scanResultsTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.scanResultsTableView.setAlternatingRowColors(True)
        self.scanResultsTableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.scanResultsTableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.scanResultsTableView.setSortingEnabled(False)
        self.scanResultsTableView.setObjectName("scanResultsTableView")
        self.scanResultsTableView.horizontalHeader().setHighlightSections(False)
        self.messageListWidget = QtWidgets.QListWidget(self.splitter)
        self.messageListWidget.setMouseTracking(True)
        self.messageListWidget.setTabKeyNavigation(False)
        self.messageListWidget.setProperty("showDropIndicator", False)
        self.messageListWidget.setAlternatingRowColors(True)
        self.messageListWidget.setSelectionRectVisible(True)
        self.messageListWidget.setObjectName("messageListWidget")
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(779, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.exportButton = QtWidgets.QPushButton(self.groupBox_2)
        self.exportButton.setIconSize(QtCore.QSize(24, 24))
        self.exportButton.setObjectName("exportButton")
        self.gridLayout_2.addWidget(self.exportButton, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        SNMPScannerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SNMPScannerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuScan = QtWidgets.QMenu(self.menubar)
        self.menuScan.setObjectName("menuScan")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        SNMPScannerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SNMPScannerWindow)
        self.statusbar.setObjectName("statusbar")
        SNMPScannerWindow.setStatusBar(self.statusbar)
        self.actionExport = QtWidgets.QAction(SNMPScannerWindow)
        self.actionExport.setEnabled(True)
        self.actionExport.setObjectName("actionExport")
        self.actionExit = QtWidgets.QAction(SNMPScannerWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionStart = QtWidgets.QAction(SNMPScannerWindow)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(SNMPScannerWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionAbout = QtWidgets.QAction(SNMPScannerWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuScan.addAction(self.actionStart)
        self.menuScan.addAction(self.actionStop)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuScan.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(SNMPScannerWindow)
        self.actionExit.triggered.connect(SNMPScannerWindow.close)
        self.actionExport.triggered.connect(self.exportButton.click)
        self.actionStart.triggered.connect(self.scanButton.click)
        self.actionStop.triggered.connect(self.stopButton.click)
        QtCore.QMetaObject.connectSlotsByName(SNMPScannerWindow)
        SNMPScannerWindow.setTabOrder(self.hostsCBox, self.communityCBox)
        SNMPScannerWindow.setTabOrder(self.communityCBox, self.scanButton)
        SNMPScannerWindow.setTabOrder(self.scanButton, self.exportButton)
        SNMPScannerWindow.setTabOrder(self.exportButton, self.stopButton)
        SNMPScannerWindow.setTabOrder(self.stopButton, self.scanResultsTableView)
        SNMPScannerWindow.setTabOrder(self.scanResultsTableView, self.messageListWidget)

    def retranslateUi(self, SNMPScannerWindow):
        _translate = QtCore.QCoreApplication.translate
        SNMPScannerWindow.setWindowTitle(_translate("SNMPScannerWindow", "SNMP Scanner"))
        self.groupBox.setTitle(_translate("SNMPScannerWindow", "Target"))
        self.scanButton.setText(_translate("SNMPScannerWindow", "Scan"))
        self.label_2.setText(_translate("SNMPScannerWindow", "Address/Network:"))
        self.label.setText(_translate("SNMPScannerWindow", "Community:"))
        self.stopButton.setText(_translate("SNMPScannerWindow", "Stop"))
        self.groupBox_2.setTitle(_translate("SNMPScannerWindow", "Result"))
        self.exportButton.setText(_translate("SNMPScannerWindow", "Export..."))
        self.menuFile.setTitle(_translate("SNMPScannerWindow", "File"))
        self.menuScan.setTitle(_translate("SNMPScannerWindow", "Scan"))
        self.menuHelp.setTitle(_translate("SNMPScannerWindow", "Help"))
        self.actionExport.setText(_translate("SNMPScannerWindow", "Export"))
        self.actionExport.setToolTip(_translate("SNMPScannerWindow", "Export results to file"))
        self.actionExit.setText(_translate("SNMPScannerWindow", "Exit"))
        self.actionExit.setToolTip(_translate("SNMPScannerWindow", "Close program"))
        self.actionStart.setText(_translate("SNMPScannerWindow", "Start"))
        self.actionStart.setToolTip(_translate("SNMPScannerWindow", "Start scan network"))
        self.actionStop.setText(_translate("SNMPScannerWindow", "Stop"))
        self.actionStop.setToolTip(_translate("SNMPScannerWindow", "Stop scan network"))
        self.actionAbout.setText(_translate("SNMPScannerWindow", "About"))
        self.actionAbout.setToolTip(_translate("SNMPScannerWindow", "About program"))

